### PR TITLE
add support for MathJax v3

### LINKED ISSUE #22: mathjax v3
It's out. Do we want to risk it?

### PR DESCRIPTION
**Pull request by christianp**
This bumps the plugin's version number to 2.0.

There's a "MathJax major version" setting, which is either 2 or 3.

The config and preamble are inserted appropriately according to the
version, and there are new defaults for version 3.

The default config for both versions now adds 'editor-rich-text' to the
list of ignored classes so MathJax doesn't run over the block editor.

I've rewritten the settings page to use add_settings_field, and store
all the options in one wp_options record, 'simple_mathjax_options'. I
think this is the preferred method, and it feels tidier.

fixes #22

### CODE REVIEW

**Comment by pkra** [comment]
Wow, this looks massive. Thanks, Christian, for essentially rewriting this!

Sam will be better suited to review this, I think.

**Comment by scoskey** [comment]
Well, it looks like a long-needed rewrite. If christian says it works, I would of course say to merge.

**Comment by christianp** [comment]
It's running on aperiodical.com, so I say it works. I'll merge it in.

**Comment by christianp** [comment]
I've updated the WordPress SVN.

**Pull request merged**
